### ISSUE TITLE
我在coding上同步了您的一个镜像站。感觉国内访问会快一些

### ISSUE THREAD

**Issue by holmeszyx** [kotlin-zhcn/kotlin-zhcn.github.io#2]
http://kotlin-zhcn.coding.me/

暂时人肉同步的github仓库

**Comment by hltj** [comment]
我这边看 http确实会比https快一些，但是都用https差异不大。
http 不安全，一些浏览器打开会有警告，我在 www.kotlincn.net 上禁用了。

https://kotlinlang.coding.me 我也曾经试过。
